name: Python exec

on:
  schedule:
    - cron:  '*/15 * * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: generate csv
      run: |
        python main.py
    - name: Commit files
      run: |
        git config --local user.email "yuto.tamur@gmail.com"
        git config --local user.name "auto"
        git commit -m "[actions]gen csv file" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
